---
title: "Vasant Marur's CV"
author: Vasant Marur
date: "`r Sys.Date()`"
params:
  pdf_mode:
    value: false
output:
  pagedown::html_resume:
    css: ['dd_cv.css', 'resume']
    self_contained: true
---

```{r,cache=FALSE, cache.path="cache/", include=FALSE}
knitr::opts_chunk$set(
  results='asis', 
  echo = FALSE
)

library(magrittr) # For the pipe
source("cv_printing_functions.r")

# Read in all data and initialize a CV printer object
CV <- create_CV_object(
  #data_location = "https://docs.google.com/spreadsheets/d/1zPRzApl5AE57R-lLE04KQchk1US88VpWPhDmKJa-srA",
  data_location = "https://docs.google.com/spreadsheets/d/18zACMXUxmmmBl3ZQpG1HxSBzab_9UkJKRcHwAtG7P0c",  
  pdf_mode = params$pdf_mode,
  resume_mode = TRUE
  )

```


```{r}
# When in pdf export mode the little dots are unaligned, so fix that with some conditional CSS.
if(params$pdf_mode) {
    cat("
<style>
:root{
  --decorator-outer-offset-left: -6.5px;
}
</style>")
}
```


Aside
================================================================================

<!--```{r} -->

<!--# Build interactive network of positions colored by section -->
<!--# and connected if they occurred in the same year -->
<!--datadrivencv::build_network_logo(CV$entries_data) -->
<!--``` -->

Contact {#contact}
--------------------------------------------------------------------------------

```{r}
CV %>% print_contact_info()
```
<br>
<br>
<br>
<br>
<br>



Language Skills {#skills}
--------------------------------------------------------------------------------

```{r}
CV %>% print_skill_bars()
```

```{r}
#if(params$pdf_mode){
#  cat("View this CV online with links at _vasantmarur.net/cv/_")
#} else {
#  cat("[<i class='fas fa-download'></i> Download a PDF of this CV](https://github.com/vmarur/cv/raw/master/vasantmarur_cv.pdf)")
#}
```

Disclaimer {#disclaimer}
--------------------------------------------------------------------------------

Made with the R package [**pagedown**](https://github.com/rstudio/pagedown). 

The source code is available [github.com/vasantm/cv](https://github.com/vasantm/cv).

Last updated on `r Sys.Date()`.



Main
================================================================================

Vasant Marur {#title}
--------------------------------------------------------------------------------

```{r}
# Note the special double pipe so we modify the CV object in place
CV %<>% print_text_block("intro") 
#CV %<>% print_section("intro") 
```

Experience {data-icon=suitcase}
--------------------------------------------------------------------------------

::: aside
```{r}
#CV %<>% print_text_block('industry_experience_aside')
```
:::

```{r}
CV %<>% print_section('industry_positions')
```

<!-- These breaks just force a new page so section doesnt get cut off -->
<br>


Education {data-icon=graduation-cap data-concise=true}
--------------------------------------------------------------------------------

```{r}
CV %<>% print_section('education')
```


Publications {data-icon=file-alt}
--------------------------------------------------------------------------------
```{r}
CV %<>% print_text_block('publication')
```

<!-- Research Experience {data-icon=laptop} -->
<!-- -------------------------------------------------------------------------------- -->

```{r}
#CV %<>% print_section('research_positions')
```


<!-- Selected Data Science Writing {data-icon=chart-line} -->
<!-- -------------------------------------------------------------------------------- -->

::: aside
```{r}
#CV %<>% print_text_block('data_science_writing_aside')
```
:::

```{r}
#CV %<>% print_section('data_science_writings')
```


<!-- Selected Publications, Posters, and Talks {data-icon=book} -->
<!-- -------------------------------------------------------------------------------- -->

```{r}
#CV %<>% print_section('academic_articles')
```



```{r}
CV %<>% print_links()
```

